spring.application.name=bookhub-backend

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bookhub_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Pa$$w0rd

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

app.jwt.secret=VGhpcklzQVZlcnlTZWN1cmVTZWNyZXRLZXlGb3JCb29rSHViMjAyNiE=
app.jwt.expiration=86400000