spring.application.name=bookhub-backend

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bookhub_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Pa$$w0rd

spring.jpa.hibernate.ddl-auto=create